language: swift
osx_image: xcode11
script: 
  - swift package generate-xcodeproj
  - bash <(curl -s https://codecov.io/bash) -X xcodellvm
  - xcodebuild -scheme TurtleBuilder-Package -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0' -enableCodeCoverage YES build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
