name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode_11.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: Generate Xcode Project
        run: swift package generate-xcodeproj
      - name: Swift test
        run: xcodebuild -scheme TurtleBuilder-Package -destination 'platform=iOS Simulator,name=iPhone XÊ€,OS=13.0' -enableCodeCoverage YES build test
